-- Seeded from src/features/find-roommates/data/roommates-data.ts. Image imports
-- remain in the React app; add Supabase Storage URLs later if images become user content.
insert into public.roommate_listings (id, type, badge_label, name, age, match_score, price_min, price_max, subtitle, location, available_date, quote, tags, housing_type, area_category, lifestyle_rhythms, move_in_horizon, bio) values
('sovann-24', 'roommate', 'ROOM SEEKER', 'Sovann', 24, 94, 220, 350, 'UX Designer • Seeking 1 roommate', 'BKK 1', 'Avail Nov 15', 'Quiet evening reader, tidy common areas, loves making drip coffee.', array['Early riser','Quiet hours','Non-smoker'], 'all', 'bkk', array['early-bird','quiet-hours','non-smoker'], 'next-30-days', 'Senior UI/UX designer working in BKK 1.'),
('sreynoch-28', 'roommate', 'ROOM SEEKER', 'Sreynoch', 28, 89, 260, 400, 'Content Producer • Seeking place/roomie', 'Daun Penh', 'Avail Dec 1', 'Sociable on weekends, respectful of deep work hours.', array['Flexible schedule','Tidy','Social weekends'], 'private-bath', 'daun-penh', array['quiet-hours','non-smoker'], '2-3-months', 'Creative producer at a digital studio in Daun Penh.'),
('sopheak-chan-26', 'roommate', 'ROOM SEEKER', 'Sopheak Chan', 26, 91, 280, 400, 'Software Dev • Seeking 1–2 roomies', 'Toul Tom Poung', 'Avail Dec 1', 'WFH engineer during weekdays. Love brewing pour-over coffee.', array['Early riser','WFH setup','Non-smoker'], 'all', 'russian-market', array['early-bird','quiet-hours','non-smoker'], '2-3-months', 'Fullstack software engineer working remotely.'),
('minimalist-studio', 'place', 'PLACE AVAILABLE', 'Minimalist Studio Room w/ Desk', null, null, 260, 260, 'Private room • Toul Kork', 'Toul Kork', 'Avail Immediately', 'Spacious private room in an eco-conscious 3BR townhouse.', array['Furnished','Quiet hours 10pm','Solar water'], 'room-available', 'toul-kork', array['quiet-hours','non-smoker'], 'next-30-days', 'Private master suite near CADT and Toul Kork market.'),
('bopha-lim-27', 'has_room', 'HAS EXTRA ROOM', 'Bopha Lim', 27, 81, 300, 450, 'Archivist • Has 2BR in BKK 2', 'BKK 2', 'Available Dec 1', 'Looking for a kindred soul to share my sunlit 2BR apartment.', array['Non-smoker','Tidy','Social weekends'], 'room-available', 'bkk', array['quiet-hours','non-smoker'], '2-3-months', 'Archivist and researcher with a spacious 2-bedroom sanctuary.'),
('riverside-colonial-flat', 'place', 'PLACE AVAILABLE', 'Riverside Colonial Flat', null, null, 380, 380, 'Daun Penh • Ready Jan 1', 'Daun Penh', 'Ready Jan 1', 'High ceilings and a tiled French balcony overlooking a peaceful side street.', array['Ensuite bath','Pet friendly','Cleaning shared'], 'entire-flat', 'daun-penh', array['pet-friendly','non-smoker'], '2-3-months', 'Restored French colonial flat facing the river breeze.')
on conflict (id) do update set name = excluded.name, match_score = excluded.match_score, price_min = excluded.price_min, price_max = excluded.price_max;
